[package]
name = "rusthello"
version = "0.1.0"
authors = ["Julien Roncaglia <julien@roncaglia.fr>"]

[dependencies]
winreg = "0.5"
byteorder = "1.2"
error-chain = "0.11"

[[bin]]
name = "rusthello"
path = "main.rs"
